# Generated by Django 4.2.1 on 2023-05-23 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.PositiveSmallIntegerField(verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('education_form', models.CharField(choices=[('Kunduzgi', 'Дневное'), ('Kechki', 'Вечернее')], max_length=32, verbose_name='Форма обучения')),
                ('language', models.CharField(choices=[('O‘zbek', 'Узбекский'), ('Rus', 'Русский')], max_length=32, verbose_name='Язык обучения')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Semestr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestr', models.PositiveSmallIntegerField(verbose_name='Семестр')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hours', models.PositiveSmallIntegerField(verbose_name='Часы')),
                ('credits', models.PositiveSmallIntegerField(verbose_name='Кредиты')),
                ('type', models.CharField(choices=[('Majburiy', 'Обязательный'), ('Tanlov', 'Выборочный'), ('Boshqa', 'Другой')], max_length=64, verbose_name='Тип предмета')),
                ('semestr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.semestr')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[("Ma'ruza", 'Лекция'), ('Amaliy', 'Практика'), ('Laboratoriya', 'Лаборатория')], max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.subject')),
            ],
            options={
                'verbose_name': 'Тип занятия',
                'verbose_name_plural': 'Типы занятий',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.subjecttype')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.teacher', verbose_name='Препод')),
            ],
        ),
        migrations.AddField(
            model_name='subjecttype',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.teacher'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='StatisticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestr_total', models.FloatField(max_length=5, verbose_name='Баллы в семестре')),
                ('final_control', models.FloatField(max_length=5, verbose_name='Итоговый контроль')),
                ('grade', models.PositiveSmallIntegerField(verbose_name='Итоговый контроль')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.statistic', verbose_name='Statistic')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Статистика[ITEM]',
                'verbose_name_plural': 'Статистика[ITEM]',
            },
        ),
        migrations.AddField(
            model_name='statistic',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stats.subject'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='teachers_subject_types',
            field=models.ManyToManyField(to='stats.teachersubjecttype', verbose_name='Препод'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.faculty', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.faculty', verbose_name='Факультет'),
        ),
    ]
